name = "line-harness"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "ab9de8440b27ffdcd70508442f09a272"

[[d1_databases]]
binding = "DB"
database_name = "line-harness"
database_id = "7efe7c20-01ae-4d65-be08-0d7b4202e8a1"

[triggers]
crons = ["*/5 * * * *"]
